# Generated by Django 4.2 on 2024-03-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('descrp', models.CharField(max_length=400)),
                ('date_added', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descrp', models.CharField(max_length=400)),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price_venta', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_add', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystock.deposito')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('fromqty', models.IntegerField()),
                ('toqty', models.IntegerField()),
                ('fromprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('toprice', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_added', models.DateField()),
                ('user', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystock.item')),
            ],
        ),
    ]
