# Generated by Django 4.2 on 2024-03-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
