# Generated by Django 4.2 on 2024-03-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0003_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.IntegerField(),
        ),
    ]
