# Generated by Django 4.2 on 2024-03-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0004_alter_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.IntegerField(choices=[(1, 'Entrada'), (2, 2), (3, 3)]),
        ),
    ]
