# Generated by Django 4.2 on 2024-04-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0005_alter_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.IntegerField(verbose_name=range(1, 2)),
        ),
    ]
