# Generated by Django 4.2 on 2024-04-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0007_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystock.rol'),
        ),
    ]
