# Generated by Django 4.2 on 2024-04-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0013_alter_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
