# Generated by Django 5.0.3 on 2024-04-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0016_alter_item_price_alter_item_price_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_add',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
